### ISSUE TITLE
One question on timeline and one on update?

### ISSUE THREAD

**Issue by muhammedhunaid** [himahuja/Research-Internships-for-Undergraduates#106]
Hi, 

Thank you for the list. I'd appreciate it very much if you could briefly answer two questions.

1. Please excuse my ignorance, when are such opportunities generally listed at primary sources for Indian Residents at Indian Universities and for International Universities?
2. I'm wondering when the update will be up for Summer 2025 opportunities here?

Best,
Muhammed

**Comment by himahuja** [comment]
The repository is updated with crowd support. Please add any opportunities you find while applying for Summer 2025, if you don't see them here already.
