### ISSUE TITLE
Add University of Warwick Statistics internship

### ISSUE THREAD

**Issue by prakharrathi25** [himahuja/Research-Internships-for-Undergraduates#44]
Can someone add this statistics research internship at the University of Warwick - https://warwick.ac.uk/fac/sci/statistics/research/internships/ 

Additionally, do you think it will be a good idea to post about some resources for each of these internships? or to make an airtable to save this data?

**Comment by prakharrathi25** [comment]
I can also add this.

**Comment by himahuja** [comment]
If you can add this, it would be wonderful. I don't have the bandwidth alone to get this done, but let me think about something that might help. 

I can close the issue once you add the internship opportunity.

**Comment by prakharrathi25** [comment]
I have added a pull request for the same. You can check it out.
