### ISSUE TITLE
Mistake in the details of ISternship Summer Student Program 

### ISSUE THREAD

**Issue by James471** [himahuja/Research-Internships-for-Undergraduates#66]
The readme states that Indian student are not eligible for the ISternship Summer Student Program. However, the FAQ page of the program(https://phd.pages.ist.ac.at/isternship/isternship-faq/) does not mention this. Instead, the "Who is eligible to apply?" section states that they accept applications from all over the world.

**Comment by himahuja** [comment]
Please feel free to update the README.

**Comment by himahuja** [comment]
I have cleared that warning, given your information.
