### ISSUE TITLE
Mistake in a link

### ISSUE THREAD

**Issue by SOUMEE2000** [himahuja/Research-Internships-for-Undergraduates#70]
[Data Visualization Programming Summer Student Internship in New York City](https://simonsfoundation.wd1.myworkdayjobs.com/en-US/simonsfoundationcareers/job/162-Fifth-Avenue/Data-Visualization-Intern--SCC_R0000579), Flatiron Institute.

The link for this is no longer working. 
Thank you so much for your efforts.

**Comment by himahuja** [comment]
I have put a note. If you find a new link, please add the pull request.
