### ISSUE TITLE
University of Alberta Research Experience (UARE)

### ISSUE THREAD

**Issue by sanskar-maddi** [himahuja/Research-Internships-for-Undergraduates#75]
University of Alberta Research Experience (UARE)
https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/ualberta-research-experience/index.html

**Comment by Nandan-N** [comment]
Only 2 IIT's are eligible tho, right?

**Comment by rageshx** [comment]
Yes only are eligible afaik

**Comment by himahuja** [comment]
You may add this as a pull request if you'd like.

**Comment by himahuja** [comment]
Added
