### ISSUE TITLE
Incorrect link in the US Section

### ISSUE THREAD

**Issue by casafurix** [himahuja/Research-Internships-for-Undergraduates#81]
The [The Smithsonian Institution Fellowship Program (SIFP)] -> (https://www.smithsonianofi.com/fellowship-opportunities/smithsonian-institution-fellowship-program/) is now incorrect, needs to be changed to the updated URL.

**Comment by casafurix** [comment]
https://fellowships.si.edu/opportunity/smithsonian-institution-fellowship-program-sifp -> this is the correct URL

**Comment by casafurix** [comment]
Also, I don't think this program is for undergraduate students:
![image](https://user-images.githubusercontent.com/77271895/206355179-c2e0f1b8-eb95-4460-a2ba-a17550b5e361.png)

**Comment by Nandan-N** [comment]
thanks for bringing it to the notice.

**Comment by himahuja** [comment]
It has been removed, thanks.
