### ISSUE TITLE
Citizenship Requirements

### ISSUE THREAD

**Issue by SG-733** [himahuja/Research-Internships-for-Undergraduates#87]
The list is great but some of the programs are only available for US Citizens or PRs ,
It would be more accessible if we could mention the program's Citizenship Requirements.

**Comment by Neptune2003** [comment]
I will work on this and get rid of non indian ones @himahuja

**Comment by SG-733** [comment]
>

**Comment by SG-733** [comment]
can we just mention if they are US Citizen Exclusive as some are open to international students in USA also.

**Comment by Neptune2003** [comment]
Ok, will mark as such

**Comment by SG-733** [comment]
yessss

**Comment by Nandan-N** [comment]
Hey, theres also other requirements too
Like many of these internships accept only junior year students

**Comment by SG-733** [comment]
Yeah, 
but for some you have to be in sophomore/junior year at the time of attending the program and not during the application that may be open during the freshmen/sophomore.

**Comment by Nandan-N** [comment]
Which year are you in and what are you applying for btw?

**Comment by Nandan-N** [comment]
Damn, same here. How's the internship application process going?

**Comment by SG-733** [comment]
Just SOPzzz

**Comment by Nandan-N** [comment]
Same here. They are a real pain!
