### ISSUE TITLE
Please add  IUSSTF-Viterbi Program

### ISSUE THREAD

**Issue by aayushsinha0706** [himahuja/Research-Internships-for-Undergraduates#88]
The Indo-US Science and Technology Forum (IUSSTF) and The Viterbi School of Engineering, University of Southern California (USC) have partnered to support the IUSSTF-Viterbi Program. This program provides opportunities to Indian students to undertake research internship at the Viterbi School of Engineering in the summer of 2023 for a period of 8 weeks.

Eligibility
- Indian students currently pursuing a Bachelors or Master’s degree at recognized institutions of higher education in India. 
- Open to students of Electrical Engineering, Electronics & Communication Engineering, Computer Engineering and Computational Sciences. 
- Grade Point Average (GPA) of 8.5 or higher (or equivalent of 3.5 GPA on a 4.0 scale); Percentage equivalent: 80% and higher.

https://iusstf.org/iusstf-viterbi-program

**Comment by himahuja** [comment]
Already on the list. Please check the list before suggesting!
